language: php

dist: bionic

php:
 - 8.2

services:
 - mysql

before_script:
 - cp .env.example .env
 - mysql -e "create database laravel"
 - composer self-update 
 - composer install --no-interaction --prefer-source
 - php artisan key:generate
 - php artisan migrate
 - npm install
 - npm run build
 - sudo apt-get update
 - sudo apt-get install -y lftp

script:
 - vendor/bin/phpunit



deploy:
  provider: script
  script: |
    echo "Starting deployment"
    lftp -e "mirror -R ./public /luishs.com/public_html/travis2; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER || { echo "Deployment failed"; exit 1; }
    echo "Deployment finished"
  skip_cleanup: true
  on:
    branch: main