language: php

dist: bionic

php:
 - 8.2

services:
 - mysql

before_script:
 - cp .env.example .env
 - mysql -e "create database laravel"
 - composer self-update 
 - composer install --no-interaction --prefer-source
 - php artisan key:generate
 - php artisan migrate
 - npm install
 - npm run build
 

script:
 - vendor/bin/phpunit

deploy:
  provider: ftp
  username: $FTP_USERNAME
  password: $FTP_PASSWORD
  server: $FTP_HOST
  local-dir: ./public  # Puedes cambiar esto si necesitas desplegar otros directorios como 'public_html'
  remote-dir: /luishs.com/public_html/travis2  # Ruta en tu servidor donde se subirán los archivos
  on:
    branch: main 