language: php

dist: bionic

php:
 - 8.2

services:
 - mysql

before_script:
 - cp .env.example .env
 - mysql -e "create database laravel"
 - composer self-update 
 - composer install --no-interaction --prefer-source
 - php artisan key:generate
 - php artisan migrate
 - npm install
 - npm run build
 - chmod +x deploy.sh

script:
 - vendor/bin/phpunit
 
after_success:
  - ./deploy.sh